---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fe-secret
  namespace: n4d-prod
spec:
  encryptedData:
    NODE_ENV: AgAtlzA7KMvWHshHzg4qPyGt7mzzRlWUJlSIFBhzz1FYVU1ptTUTfebvPemC4gCcJQ5ZqpjPSDW4YWhOXV7v2MoLJp4Yom482JBfwAGgPZLPeSSSWlNweZJMKzG7ZuEcoqCAcSx6Md2CcXZE5N9qF1Ruhu+EDWCSlCQ+O/8N9nn+xsmBto/sEl5rWndGlvSGVjDsJ2b0NkfN+tet4crXbNwb4e01clJH6byTFC0w1g4SLnaxvDjcIIyHCEEhRh8pm4cinphRczQC7YghZfPaRP/kBAKpYQW5DHeq0RMI/9VlTdJih3A1zPXeTeUAKdFQeesz5mnp28tI4opMyW2O01QHzR1G9a++3n0VIu5W+WvR5p7rpYca19q8zgOCNYjazZ1/tZBn4LHEfZMGswDc+QnlIlHXAsBbDLJsNJbjz07b2vnVKKIcT/g/EA6TXZMJAITH6NI0MlkpyrZm0m1nXec9Ri7nfF86+PhJtlFiio5wMnSnY+4tAO86zo0wjChr/AtbegCBemZ4/bZlCpXwR5rP61z1tAD1tLWg5igxTnQTA1AxjBfV07pArlXqkZxZnZ5HuVngQVVwz1Y8aDFDePGgb0mMnXGxTQa8Uf1yvulcMWEGmmH33eOxjCOhX2BFtWQEiyt/fmxESe110HAtt8vKNnwNkHf49Ie8tQ7FWGZReFU87s+TGPnMRKrrmU0lyu9w6M31StGb23VF
    PORT: AgAQmM3GBjtXZmNRxneSyu3k5e+7WiZOTH20pY9iRiWyXQUxrIM287jIDHK2YXE+I2iQixmvK6qY7UDaYn85NuIySxzyA+HD6zhtGpr7ZR/xN38zNYE6Jqf5y2nZcdU8Afg2HIwhLaWkQHC4ymajuJfwfs6ivgkjFbI1i5yi6NnvJiC/ZYzJaIJTJwoK3iWqXxU525L7jTELuc5JoC+paHqkPwxJEBSmQPOprXjltRLmJn+rMk41XsZHAga+DabAD0D2ag7IPi6HZjUBht4QFQJJznIIE4Q7KP57f0xPVFvBVeTL1aTU8SR6+cZABc6PaogD3Qzmp2i77hSt+KJ4zpte67pZdmQp7/xliqO6GTqYr/rP+JT+3FTufq0lO5uNRKwg9DHMmpcdYm/qnkdIBm0vOSniMxsd1SnPcL17n+vlrGt2F5wScxD8GQ6UjUrDsckDL4IHnRlUhhgM1ZXTslsj2C36kVDK9/65Gk6gXsPASEB1hBvw3iE8Zkhy94uuNXKA8+Y2TcHxSFXFBj/tzctHxeZlTX1x2gLFc7nr/6K9Hhehrr207H1Do0EopWtac/3pCT1XRyjOR10M+MxRV7kSmXT9Lu8X6KWrFoK+aYVBOiPxP172ikMHWaVic2odVYUgoau/MDGXNZG0J8rTu2HFLJsP1sPhtf8McaFJVVUNr5pKGVY/R/1DLYbcYZB49FzP4gPG
  template:
    metadata:
      name: fe-secret
      namespace: n4d-prod
