---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: n4d-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBbbyfKgz2PYre0m5FueuFU6eXMmWHlZv3n+7j6NilC7hdObfpVczh++HZBeSyjPJjhteVr8KXf09q7x+pbfuY5gbsEslz4F10XkVigUykngah7dsfg3PS4CksRrbuMIkaurlPLGqIpJQ0qBCp82Mv4JHEJJmCrmw+dY49rKkzMKakdLZVRhgUkU9pMM/am6RW5HYJkNr88dG0QthvXRHcLZPuAxFmaqnEldpGNeK/jkv4H1QQbbklnIcAgBcOfSt+6P9fDLs8Jwy0RLyhWrE9AxOp+INAF0uKfylkhz8vdUXa1JhNlO+StMnnvcnbw9hqPXEZJS2HHkNM9F0Ah/SjmUmjsmejjgPc9N19fJrIRloxlTY+IBFCZpAP2MMEaWDqLDbuWpORpzAAzTXApROzxzYNt+gcihNoQGcNPYPZG9zmn05kgVoL4FUHiHc7YQEKhch4wLA4VIZpEKalXL/OST2FnhkkLvMR31x9epTgHo3QCPSiXYKtqKijHma8xmVu3D0LH5tJ6G/85gL9QjztgLGiAchzbshcoRY3ZCjn9YTL3sLd4Pld4Q4Zj+s703n/LCNzpbnyOir8Y4jQDH/v/l7bwAe551ZRB7EfHhy0J8ccHTC2ykwuTNUiGI0mgp8r7wFXaYelqAiKYeWYv2SpRbVZOAWNS9Bu4o06B2ILTBySGHjl8phFQv3kWBGjZqufbKz20GRTN24fXdrJbUrhh8pbuImS22eo8RX/VEjY0DfeBtbSvYOxWbjlihFfS2eQ2InpKTQtikaA89/Zc9QgPbUT7B3mCckH9hBEmDjfCTeR+Z1pzIl1eoc200Hr9SdgiL3MxAEQXqBEcJfS3
  template:
    metadata:
      name: ghcr-secret
      namespace: n4d-prod
    type: kubernetes.io/dockerconfigjson
