---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-backup-alerts
  namespace: n4d-prod
spec:
  encryptedData:
    SLACK_OPS_WEBHOOK_URL: AgBf7ztLK9B11Y7f1dzLOUuH8oOoJIe0w1AoBY1GmVncB21FmLVDUQyWnlDOU8n6e933YV4me9K49GUm5YT/TWk7Th9IwLaWXBfanEPuXW2dQzOE19qbMvJ7jxIcrK+cWhuZQJrMWwqHvqtjn0XWQ5n9q3qL2lRwdsao+3zsTMa1IXDn1hKgyxhAIWScOi3w0lC0Q1fCgf4Gmu3f3r59PoA5CkQkvucdV1qcy/JI6nkGMtkV1hLCMhzxmnrpx8U+3VaFJ4RP1hzKpmidHOcZs6jtSSuZFWVCH4vRHsJpgFHajUkXrwdyxc2UwpETpfm90ZKnjzPO7oV5kgwMPzmjiJeIdLL3ckkXoRL25WrIxonfxOMHPaPOgSZLon09VQCQ3YdPfy14D8dB3Kcvl7Wd36M6YdUMLFrfjq2rElC6aBmRYbPYgpkN7PNR+1qDN1ZJGyQ0+tjedTaoVCbqwIX98a/ba92ZqhAsufLBPeywPOjF3MKxa4QYAm6TAZx7eguGZ+W74r3fE5Sh63J+MOtjPFtBkygS1b/k1tKG/lbsaPV2ldvqp4DZAfm5IFEDMjNIyxpA2LToTz3VUwvgIyZdgcPXXnw6BaauBiTzdob30h9EIbCO+pu5+4zNVBgLh/pA+Od2Cx0lRc2rseuwXM2pQn2mAwG00CTvK/ikxCyWvFlBLFH/EZRvll8P2f/ZY6UPlq+6vmSikdYzj851zp0xEwovzYN2IF9qaN8Sln3uq1bfG+SF1W2L1muC2z+36czP5l0Vb+p6Lk8gnVie9zH8jnZXAKfzmiJELWNHwQrOP3+PFl8=
  template:
    metadata:
      name: pg-backup-alerts
      namespace: n4d-prod
